-- ============================================================
-- V1__create_schema.sql
-- Criação de todas as tabelas do sistema coffee-order-app
-- ============================================================

-- Tabela de usuários
CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    email       VARCHAR(255),
    password    VARCHAR(255),
    role        VARCHAR(50),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de ingredientes
CREATE TABLE ingredient (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    type            VARCHAR(50) NOT NULL,
    price           DECIMAL(10,2) NOT NULL,
    stock_quantity  INTEGER NOT NULL DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE
);

-- Tabela de sabores clássicos
CREATE TABLE classic_flavor (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    base_price  DECIMAL(10,2) NOT NULL
);

-- Tabela de junção: sabores clássicos <-> ingredientes
CREATE TABLE classic_flavor_ingredients (
    flavor_id       BIGINT NOT NULL,
    ingredient_id   BIGINT NOT NULL,
    PRIMARY KEY (flavor_id, ingredient_id),
    CONSTRAINT fk_cfi_flavor FOREIGN KEY (flavor_id) REFERENCES classic_flavor(id),
    CONSTRAINT fk_cfi_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredient(id)
);

-- Tabela de pedidos
CREATE TABLE coffee_order (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generated_name      VARCHAR(255),
    total_price         DECIMAL(10,2),
    matched_flavor_id   BIGINT,
    CONSTRAINT fk_order_flavor FOREIGN KEY (matched_flavor_id) REFERENCES classic_flavor(id)
);

-- Tabela de junção: pedidos <-> ingredientes base
CREATE TABLE coffee_order_base_ingredients (
    coffee_order_id     BIGINT NOT NULL,
    base_ingredients_id BIGINT NOT NULL,
    CONSTRAINT fk_cobi_order FOREIGN KEY (coffee_order_id) REFERENCES coffee_order(id),
    CONSTRAINT fk_cobi_ingredient FOREIGN KEY (base_ingredients_id) REFERENCES ingredient(id)
);

-- Tabela de junção: pedidos <-> ingredientes adicionais
CREATE TABLE coffee_order_additional_ingredients (
    coffee_order_id             BIGINT NOT NULL,
    additional_ingredients_id   BIGINT NOT NULL,
    CONSTRAINT fk_coai_order FOREIGN KEY (coffee_order_id) REFERENCES coffee_order(id),
    CONSTRAINT fk_coai_ingredient FOREIGN KEY (additional_ingredients_id) REFERENCES ingredient(id)
);
